# ATHARVA NALGE

In [9]:
import numpy as np

# Define the sigmoid function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Input data (XOR truth table)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Output data
Y = np.array([[0], [1], [1], [0]])

# Initialize weights and biases
input_size = 2
hidden_size = 4
output_size = 1

# Weights and biases for the input and hidden layer
w_input_hidden = np.random.uniform(size=(input_size, hidden_size))
b_input_hidden = np.zeros((1, hidden_size))

# Weights and biases for the hidden and output layer
w_hidden_output = np.random.uniform(size=(hidden_size, output_size))
b_hidden_output = np.zeros((1, output_size))

learning_rate = 0.9
epochs = 1000

# Training the neural network
for epoch in range(epochs):
    # Forward propagation
    hidden_input = np.dot(X, w_input_hidden) + b_input_hidden
    hidden_output = sigmoid(hidden_input)
    output_layer_input = np.dot(hidden_output, w_hidden_output) + b_hidden_output
    output_layer_output = sigmoid(output_layer_input)

    # Calculate the loss
    loss = Y - output_layer_output

    # Backpropagation
    d_output = loss * sigmoid_derivative(output_layer_output)
    error_hidden_layer = d_output.dot(w_hidden_output.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_output)

    # Update weights and biases
    w_hidden_output += hidden_output.T.dot(d_output) * learning_rate
    w_input_hidden += X.T.dot(d_hidden_layer) * learning_rate
    b_hidden_output += np.sum(d_output, axis=0, keepdims=True) * learning_rate
    b_input_hidden += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

    # Print the predictions for this epoch
    print(f"Epoch {epoch+1} - Predicted Output:")
    print(output_layer_output)

# Testing the final trained neural network
hidden_input = np.dot(X, w_input_hidden) + b_input_hidden
hidden_output = sigmoid(hidden_input)
output_layer_input = np.dot(hidden_output, w_hidden_output) + b_hidden_output
output_layer_output = sigmoid(output_layer_input)

print("Final Predicted Output:")
print(output_layer_output)


Epoch 1 - Predicted Output:
[[0.71005988]
 [0.76626904]
 [0.76689112]
 [0.80584202]]
Epoch 2 - Predicted Output:
[[0.62510962]
 [0.67755223]
 [0.67902951]
 [0.71774112]]
Epoch 3 - Predicted Output:
[[0.55112476]
 [0.59586305]
 [0.59810998]
 [0.63229693]]
Epoch 4 - Predicted Output:
[[0.50643161]
 [0.54506496]
 [0.54773208]
 [0.57752305]]
Epoch 5 - Predicted Output:
[[0.48527203]
 [0.5208136 ]
 [0.52364139]
 [0.55102149]]
Epoch 6 - Predicted Output:
[[0.47604226]
 [0.51030496]
 [0.51317372]
 [0.53948435]]
Epoch 7 - Predicted Output:
[[0.47205811]
 [0.50588645]
 [0.50874651]
 [0.53463255]]
Epoch 8 - Predicted Output:
[[0.47030612]
 [0.50406931]
 [0.50690022]
 [0.5326454 ]]
Epoch 9 - Predicted Output:
[[0.46949617]
 [0.50335354]
 [0.50614688]
 [0.53187268]]
Epoch 10 - Predicted Output:
[[0.46908207]
 [0.50310292]
 [0.50585532]
 [0.53161321]]
Epoch 11 - Predicted Output:
[[0.46883332]
 [0.50304874]
 [0.50575897]
 [0.53157063]]
Epoch 12 - Predicted Output:
[[0.46865283]
 [0.5030778 ]
 [0.50

Epoch 830 - Predicted Output:
[[0.07278571]
 [0.9372644 ]
 [0.93783684]
 [0.06556689]]
Epoch 831 - Predicted Output:
[[0.07270207]
 [0.93734544]
 [0.93791644]
 [0.06547639]]
Epoch 832 - Predicted Output:
[[0.07261868]
 [0.93742621]
 [0.93799577]
 [0.0653862 ]]
Epoch 833 - Predicted Output:
[[0.07253555]
 [0.9375067 ]
 [0.93807485]
 [0.06529633]]
Epoch 834 - Predicted Output:
[[0.07245267]
 [0.93758693]
 [0.93815366]
 [0.06520676]]
Epoch 835 - Predicted Output:
[[0.07237004]
 [0.9376669 ]
 [0.93823221]
 [0.06511751]]
Epoch 836 - Predicted Output:
[[0.07228766]
 [0.9377466 ]
 [0.9383105 ]
 [0.06502856]]
Epoch 837 - Predicted Output:
[[0.07220553]
 [0.93782603]
 [0.93838854]
 [0.06493991]]
Epoch 838 - Predicted Output:
[[0.07212364]
 [0.93790521]
 [0.93846632]
 [0.06485157]]
Epoch 839 - Predicted Output:
[[0.07204201]
 [0.93798412]
 [0.93854384]
 [0.06476353]]
Epoch 840 - Predicted Output:
[[0.07196061]
 [0.93806278]
 [0.93862111]
 [0.06467579]]
Epoch 841 - Predicted Output:
[[0.07187946]